name: Go Build and Release

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  goreleaser:
    name: Release Project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Build with Go (Linux Only)
        run: |
          GOOS=linux GOARCH=amd64 go build -o ./build/backhaul_amd64
          GOOS=linux GOARCH=arm64 go build -o ./build/backhaul_arm64

      - name: Package files (Linux Only)
        run: |
          tar -czvf backhaul_amd64.tar.gz -C ./build backhaul_amd64
          tar -czvf backhaul_arm64.tar.gz -C ./build backhaul_arm64
          mkdir -p output
          mv backhaul_amd64.tar.gz output/
          mv backhaul_arm64.tar.gz output/

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: backhaul_linux_artifacts
          path: output/

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: '~> v2'
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
